'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.30319.33440.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.sat.gob.mx/cfd/3", IsNullable:=false)>  _
Partial Public Class Comprobante
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged

    <System.Xml.Serialization.XmlAttribute("schemaLocation", [Namespace]:="http://www.w3.org/2001/XMLSchema-instance")> _
    Public SchemaLocation As String = "http://www.sat.gob.mx/cfd/3  http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv32.xsd "

    Private emisorField As ComprobanteEmisor
    
    Private receptorField As ComprobanteReceptor
    
    Private conceptosField() As ComprobanteConcepto
    
    Private impuestosField As ComprobanteImpuestos
    
    Private complementoField As ComprobanteComplemento
    
    Private addendaField As ComprobanteAddenda
    
    Private versionField As String
    
    Private serieField As String
    
    Private folioField As String
    
    Private fechaField As Date
    
    Private selloField As String
    
    Private formaDePagoField As String
    
    Private noCertificadoField As String
    
    Private certificadoField As String
    
    Private condicionesDePagoField As String
    
    Private subTotalField As Decimal
    
    Private descuentoField As Decimal
    
    Private descuentoFieldSpecified As Boolean
    
    Private motivoDescuentoField As String
    
    Private tipoCambioField As String
    
    Private monedaField As String
    
    Private totalField As Decimal
    
    Private tipoDeComprobanteField As ComprobanteTipoDeComprobante
    
    Private metodoDePagoField As String
    
    Private lugarExpedicionField As String
    
    Private numCtaPagoField As String
    
    Private folioFiscalOrigField As String
    
    Private serieFolioFiscalOrigField As String
    
    Private fechaFolioFiscalOrigField As Date
    
    Private fechaFolioFiscalOrigFieldSpecified As Boolean
    
    Private montoFolioFiscalOrigField As Decimal
    
    Private montoFolioFiscalOrigFieldSpecified As Boolean
    
    Public Sub New()
        MyBase.New
        Me.versionField = "3.2"
    End Sub
    
    '''<remarks/>
    Public Property Emisor() As ComprobanteEmisor
        Get
            Return Me.emisorField
        End Get
        Set
            Me.emisorField = value
            Me.RaisePropertyChanged("Emisor")
        End Set
    End Property
    
    '''<remarks/>
    Public Property Receptor() As ComprobanteReceptor
        Get
            Return Me.receptorField
        End Get
        Set
            Me.receptorField = value
            Me.RaisePropertyChanged("Receptor")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("Concepto", IsNullable:=false)>  _
    Public Property Conceptos() As ComprobanteConcepto()
        Get
            Return Me.conceptosField
        End Get
        Set
            Me.conceptosField = value
            Me.RaisePropertyChanged("Conceptos")
        End Set
    End Property
    
    '''<remarks/>
    Public Property Impuestos() As ComprobanteImpuestos
        Get
            Return Me.impuestosField
        End Get
        Set
            Me.impuestosField = value
            Me.RaisePropertyChanged("Impuestos")
        End Set
    End Property
    
    '''<remarks/>
    Public Property Complemento() As ComprobanteComplemento
        Get
            Return Me.complementoField
        End Get
        Set
            Me.complementoField = value
            Me.RaisePropertyChanged("Complemento")
        End Set
    End Property
    
    '''<remarks/>
    Public Property Addenda() As ComprobanteAddenda
        Get
            Return Me.addendaField
        End Get
        Set
            Me.addendaField = value
            Me.RaisePropertyChanged("Addenda")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property version() As String
        Get
            Return Me.versionField
        End Get
        Set
            Me.versionField = value
            Me.RaisePropertyChanged("version")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property serie() As String
        Get
            Return Me.serieField
        End Get
        Set
            Me.serieField = value
            Me.RaisePropertyChanged("serie")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property folio() As String
        Get
            Return Me.folioField
        End Get
        Set
            Me.folioField = value
            Me.RaisePropertyChanged("folio")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property fecha() As Date
        Get
            Return Me.fechaField
        End Get
        Set
            Me.fechaField = value
            Me.RaisePropertyChanged("fecha")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property sello() As String
        Get
            Return Me.selloField
        End Get
        Set
            Me.selloField = value
            Me.RaisePropertyChanged("sello")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property formaDePago() As String
        Get
            Return Me.formaDePagoField
        End Get
        Set
            Me.formaDePagoField = value
            Me.RaisePropertyChanged("formaDePago")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property noCertificado() As String
        Get
            Return Me.noCertificadoField
        End Get
        Set
            Me.noCertificadoField = value
            Me.RaisePropertyChanged("noCertificado")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property certificado() As String
        Get
            Return Me.certificadoField
        End Get
        Set
            Me.certificadoField = value
            Me.RaisePropertyChanged("certificado")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property condicionesDePago() As String
        Get
            Return Me.condicionesDePagoField
        End Get
        Set
            Me.condicionesDePagoField = value
            Me.RaisePropertyChanged("condicionesDePago")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property subTotal() As Decimal
        Get
            Return Me.subTotalField
        End Get
        Set
            Me.subTotalField = value
            Me.RaisePropertyChanged("subTotal")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property descuento() As Decimal
        Get
            Return Me.descuentoField
        End Get
        Set
            Me.descuentoField = value
            Me.RaisePropertyChanged("descuento")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property descuentoSpecified() As Boolean
        Get
            Return Me.descuentoFieldSpecified
        End Get
        Set
            Me.descuentoFieldSpecified = value
            Me.RaisePropertyChanged("descuentoSpecified")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property motivoDescuento() As String
        Get
            Return Me.motivoDescuentoField
        End Get
        Set
            Me.motivoDescuentoField = value
            Me.RaisePropertyChanged("motivoDescuento")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property TipoCambio() As String
        Get
            Return Me.tipoCambioField
        End Get
        Set
            Me.tipoCambioField = value
            Me.RaisePropertyChanged("TipoCambio")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Moneda() As String
        Get
            Return Me.monedaField
        End Get
        Set
            Me.monedaField = value
            Me.RaisePropertyChanged("Moneda")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property total() As Decimal
        Get
            Return Me.totalField
        End Get
        Set
            Me.totalField = value
            Me.RaisePropertyChanged("total")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property tipoDeComprobante() As ComprobanteTipoDeComprobante
        Get
            Return Me.tipoDeComprobanteField
        End Get
        Set
            Me.tipoDeComprobanteField = value
            Me.RaisePropertyChanged("tipoDeComprobante")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property metodoDePago() As String
        Get
            Return Me.metodoDePagoField
        End Get
        Set
            Me.metodoDePagoField = value
            Me.RaisePropertyChanged("metodoDePago")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property LugarExpedicion() As String
        Get
            Return Me.lugarExpedicionField
        End Get
        Set
            Me.lugarExpedicionField = value
            Me.RaisePropertyChanged("LugarExpedicion")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property NumCtaPago() As String
        Get
            Return Me.numCtaPagoField
        End Get
        Set
            Me.numCtaPagoField = value
            Me.RaisePropertyChanged("NumCtaPago")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property FolioFiscalOrig() As String
        Get
            Return Me.folioFiscalOrigField
        End Get
        Set
            Me.folioFiscalOrigField = value
            Me.RaisePropertyChanged("FolioFiscalOrig")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property SerieFolioFiscalOrig() As String
        Get
            Return Me.serieFolioFiscalOrigField
        End Get
        Set
            Me.serieFolioFiscalOrigField = value
            Me.RaisePropertyChanged("SerieFolioFiscalOrig")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property FechaFolioFiscalOrig() As Date
        Get
            Return Me.fechaFolioFiscalOrigField
        End Get
        Set
            Me.fechaFolioFiscalOrigField = value
            Me.RaisePropertyChanged("FechaFolioFiscalOrig")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property FechaFolioFiscalOrigSpecified() As Boolean
        Get
            Return Me.fechaFolioFiscalOrigFieldSpecified
        End Get
        Set
            Me.fechaFolioFiscalOrigFieldSpecified = value
            Me.RaisePropertyChanged("FechaFolioFiscalOrigSpecified")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property MontoFolioFiscalOrig() As Decimal
        Get
            Return Me.montoFolioFiscalOrigField
        End Get
        Set
            Me.montoFolioFiscalOrigField = value
            Me.RaisePropertyChanged("MontoFolioFiscalOrig")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property MontoFolioFiscalOrigSpecified() As Boolean
        Get
            Return Me.montoFolioFiscalOrigFieldSpecified
        End Get
        Set
            Me.montoFolioFiscalOrigFieldSpecified = value
            Me.RaisePropertyChanged("MontoFolioFiscalOrigSpecified")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
Partial Public Class ComprobanteEmisor
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private domicilioFiscalField As t_UbicacionFiscal
    
    Private expedidoEnField As t_Ubicacion
    
    Private regimenFiscalField() As ComprobanteEmisorRegimenFiscal
    
    Private rfcField As String
    
    Private nombreField As String
    
    '''<remarks/>
    Public Property DomicilioFiscal() As t_UbicacionFiscal
        Get
            Return Me.domicilioFiscalField
        End Get
        Set
            Me.domicilioFiscalField = value
            Me.RaisePropertyChanged("DomicilioFiscal")
        End Set
    End Property
    
    '''<remarks/>
    Public Property ExpedidoEn() As t_Ubicacion
        Get
            Return Me.expedidoEnField
        End Get
        Set
            Me.expedidoEnField = value
            Me.RaisePropertyChanged("ExpedidoEn")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("RegimenFiscal")>  _
    Public Property RegimenFiscal() As ComprobanteEmisorRegimenFiscal()
        Get
            Return Me.regimenFiscalField
        End Get
        Set
            Me.regimenFiscalField = value
            Me.RaisePropertyChanged("RegimenFiscal")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property rfc() As String
        Get
            Return Me.rfcField
        End Get
        Set
            Me.rfcField = value
            Me.RaisePropertyChanged("rfc")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property nombre() As String
        Get
            Return Me.nombreField
        End Get
        Set
            Me.nombreField = value
            Me.RaisePropertyChanged("nombre")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
Partial Public Class t_UbicacionFiscal
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private calleField As String
    
    Private noExteriorField As String
    
    Private noInteriorField As String
    
    Private coloniaField As String
    
    Private localidadField As String
    
    Private referenciaField As String
    
    Private municipioField As String
    
    Private estadoField As String
    
    Private paisField As String
    
    Private codigoPostalField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property calle() As String
        Get
            Return Me.calleField
        End Get
        Set
            Me.calleField = value
            Me.RaisePropertyChanged("calle")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property noExterior() As String
        Get
            Return Me.noExteriorField
        End Get
        Set
            Me.noExteriorField = value
            Me.RaisePropertyChanged("noExterior")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property noInterior() As String
        Get
            Return Me.noInteriorField
        End Get
        Set
            Me.noInteriorField = value
            Me.RaisePropertyChanged("noInterior")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property colonia() As String
        Get
            Return Me.coloniaField
        End Get
        Set
            Me.coloniaField = value
            Me.RaisePropertyChanged("colonia")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property localidad() As String
        Get
            Return Me.localidadField
        End Get
        Set
            Me.localidadField = value
            Me.RaisePropertyChanged("localidad")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property referencia() As String
        Get
            Return Me.referenciaField
        End Get
        Set
            Me.referenciaField = value
            Me.RaisePropertyChanged("referencia")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property municipio() As String
        Get
            Return Me.municipioField
        End Get
        Set
            Me.municipioField = value
            Me.RaisePropertyChanged("municipio")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property estado() As String
        Get
            Return Me.estadoField
        End Get
        Set
            Me.estadoField = value
            Me.RaisePropertyChanged("estado")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property pais() As String
        Get
            Return Me.paisField
        End Get
        Set
            Me.paisField = value
            Me.RaisePropertyChanged("pais")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property codigoPostal() As String
        Get
            Return Me.codigoPostalField
        End Get
        Set
            Me.codigoPostalField = value
            Me.RaisePropertyChanged("codigoPostal")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
Partial Public Class t_InformacionAduanera
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private numeroField As String
    
    Private fechaField As Date
    
    Private aduanaField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property numero() As String
        Get
            Return Me.numeroField
        End Get
        Set
            Me.numeroField = value
            Me.RaisePropertyChanged("numero")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="date")>  _
    Public Property fecha() As Date
        Get
            Return Me.fechaField
        End Get
        Set
            Me.fechaField = value
            Me.RaisePropertyChanged("fecha")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property aduana() As String
        Get
            Return Me.aduanaField
        End Get
        Set
            Me.aduanaField = value
            Me.RaisePropertyChanged("aduana")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
Partial Public Class t_Ubicacion
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private calleField As String
    
    Private noExteriorField As String
    
    Private noInteriorField As String
    
    Private coloniaField As String
    
    Private localidadField As String
    
    Private referenciaField As String
    
    Private municipioField As String
    
    Private estadoField As String
    
    Private paisField As String
    
    Private codigoPostalField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property calle() As String
        Get
            Return Me.calleField
        End Get
        Set
            Me.calleField = value
            Me.RaisePropertyChanged("calle")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property noExterior() As String
        Get
            Return Me.noExteriorField
        End Get
        Set
            Me.noExteriorField = value
            Me.RaisePropertyChanged("noExterior")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property noInterior() As String
        Get
            Return Me.noInteriorField
        End Get
        Set
            Me.noInteriorField = value
            Me.RaisePropertyChanged("noInterior")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property colonia() As String
        Get
            Return Me.coloniaField
        End Get
        Set
            Me.coloniaField = value
            Me.RaisePropertyChanged("colonia")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property localidad() As String
        Get
            Return Me.localidadField
        End Get
        Set
            Me.localidadField = value
            Me.RaisePropertyChanged("localidad")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property referencia() As String
        Get
            Return Me.referenciaField
        End Get
        Set
            Me.referenciaField = value
            Me.RaisePropertyChanged("referencia")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property municipio() As String
        Get
            Return Me.municipioField
        End Get
        Set
            Me.municipioField = value
            Me.RaisePropertyChanged("municipio")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property estado() As String
        Get
            Return Me.estadoField
        End Get
        Set
            Me.estadoField = value
            Me.RaisePropertyChanged("estado")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property pais() As String
        Get
            Return Me.paisField
        End Get
        Set
            Me.paisField = value
            Me.RaisePropertyChanged("pais")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property codigoPostal() As String
        Get
            Return Me.codigoPostalField
        End Get
        Set
            Me.codigoPostalField = value
            Me.RaisePropertyChanged("codigoPostal")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
Partial Public Class ComprobanteEmisorRegimenFiscal
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private regimenField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Regimen() As String
        Get
            Return Me.regimenField
        End Get
        Set
            Me.regimenField = value
            Me.RaisePropertyChanged("Regimen")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
Partial Public Class ComprobanteReceptor
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private domicilioField As t_Ubicacion
    
    Private rfcField As String
    
    Private nombreField As String
    
    '''<remarks/>
    Public Property Domicilio() As t_Ubicacion
        Get
            Return Me.domicilioField
        End Get
        Set
            Me.domicilioField = value
            Me.RaisePropertyChanged("Domicilio")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property rfc() As String
        Get
            Return Me.rfcField
        End Get
        Set
            Me.rfcField = value
            Me.RaisePropertyChanged("rfc")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property nombre() As String
        Get
            Return Me.nombreField
        End Get
        Set
            Me.nombreField = value
            Me.RaisePropertyChanged("nombre")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
Partial Public Class ComprobanteConcepto
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private itemsField() As Object
    
    Private cantidadField As Decimal
    
    Private unidadField As String
    
    Private noIdentificacionField As String
    
    Private descripcionField As String
    
    Private valorUnitarioField As Decimal
    
    Private importeField As Decimal
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("ComplementoConcepto", GetType(ComprobanteConceptoComplementoConcepto)),  _
     System.Xml.Serialization.XmlElementAttribute("CuentaPredial", GetType(ComprobanteConceptoCuentaPredial)),  _
     System.Xml.Serialization.XmlElementAttribute("InformacionAduanera", GetType(t_InformacionAduanera)),  _
     System.Xml.Serialization.XmlElementAttribute("Parte", GetType(ComprobanteConceptoParte))>  _
    Public Property Items() As Object()
        Get
            Return Me.itemsField
        End Get
        Set
            Me.itemsField = value
            Me.RaisePropertyChanged("Items")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property cantidad() As Decimal
        Get
            Return Me.cantidadField
        End Get
        Set
            Me.cantidadField = value
            Me.RaisePropertyChanged("cantidad")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property unidad() As String
        Get
            Return Me.unidadField
        End Get
        Set
            Me.unidadField = value
            Me.RaisePropertyChanged("unidad")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property noIdentificacion() As String
        Get
            Return Me.noIdentificacionField
        End Get
        Set
            Me.noIdentificacionField = value
            Me.RaisePropertyChanged("noIdentificacion")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property descripcion() As String
        Get
            Return Me.descripcionField
        End Get
        Set
            Me.descripcionField = value
            Me.RaisePropertyChanged("descripcion")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property valorUnitario() As Decimal
        Get
            Return Me.valorUnitarioField
        End Get
        Set
            Me.valorUnitarioField = value
            Me.RaisePropertyChanged("valorUnitario")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property importe() As Decimal
        Get
            Return Me.importeField
        End Get
        Set
            Me.importeField = value
            Me.RaisePropertyChanged("importe")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
Partial Public Class ComprobanteConceptoComplementoConcepto
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private anyField() As System.Xml.XmlElement
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAnyElementAttribute()>  _
    Public Property Any() As System.Xml.XmlElement()
        Get
            Return Me.anyField
        End Get
        Set
            Me.anyField = value
            Me.RaisePropertyChanged("Any")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
Partial Public Class ComprobanteConceptoCuentaPredial
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private numeroField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property numero() As String
        Get
            Return Me.numeroField
        End Get
        Set
            Me.numeroField = value
            Me.RaisePropertyChanged("numero")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
Partial Public Class ComprobanteConceptoParte
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private informacionAduaneraField() As t_InformacionAduanera
    
    Private cantidadField As Decimal
    
    Private unidadField As String
    
    Private noIdentificacionField As String
    
    Private descripcionField As String
    
    Private valorUnitarioField As Decimal
    
    Private valorUnitarioFieldSpecified As Boolean
    
    Private importeField As Decimal
    
    Private importeFieldSpecified As Boolean
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("InformacionAduanera")>  _
    Public Property InformacionAduanera() As t_InformacionAduanera()
        Get
            Return Me.informacionAduaneraField
        End Get
        Set
            Me.informacionAduaneraField = value
            Me.RaisePropertyChanged("InformacionAduanera")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property cantidad() As Decimal
        Get
            Return Me.cantidadField
        End Get
        Set
            Me.cantidadField = value
            Me.RaisePropertyChanged("cantidad")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property unidad() As String
        Get
            Return Me.unidadField
        End Get
        Set
            Me.unidadField = value
            Me.RaisePropertyChanged("unidad")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property noIdentificacion() As String
        Get
            Return Me.noIdentificacionField
        End Get
        Set
            Me.noIdentificacionField = value
            Me.RaisePropertyChanged("noIdentificacion")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property descripcion() As String
        Get
            Return Me.descripcionField
        End Get
        Set
            Me.descripcionField = value
            Me.RaisePropertyChanged("descripcion")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property valorUnitario() As Decimal
        Get
            Return Me.valorUnitarioField
        End Get
        Set
            Me.valorUnitarioField = value
            Me.RaisePropertyChanged("valorUnitario")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property valorUnitarioSpecified() As Boolean
        Get
            Return Me.valorUnitarioFieldSpecified
        End Get
        Set
            Me.valorUnitarioFieldSpecified = value
            Me.RaisePropertyChanged("valorUnitarioSpecified")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property importe() As Decimal
        Get
            Return Me.importeField
        End Get
        Set
            Me.importeField = value
            Me.RaisePropertyChanged("importe")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property importeSpecified() As Boolean
        Get
            Return Me.importeFieldSpecified
        End Get
        Set
            Me.importeFieldSpecified = value
            Me.RaisePropertyChanged("importeSpecified")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
Partial Public Class ComprobanteImpuestos
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private retencionesField() As ComprobanteImpuestosRetencion
    
    Private trasladosField() As ComprobanteImpuestosTraslado
    
    Private totalImpuestosRetenidosField As Decimal
    
    Private totalImpuestosRetenidosFieldSpecified As Boolean
    
    Private totalImpuestosTrasladadosField As Decimal
    
    Private totalImpuestosTrasladadosFieldSpecified As Boolean
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("Retencion", IsNullable:=false)>  _
    Public Property Retenciones() As ComprobanteImpuestosRetencion()
        Get
            Return Me.retencionesField
        End Get
        Set
            Me.retencionesField = value
            Me.RaisePropertyChanged("Retenciones")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("Traslado", IsNullable:=false)>  _
    Public Property Traslados() As ComprobanteImpuestosTraslado()
        Get
            Return Me.trasladosField
        End Get
        Set
            Me.trasladosField = value
            Me.RaisePropertyChanged("Traslados")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property totalImpuestosRetenidos() As Decimal
        Get
            Return Me.totalImpuestosRetenidosField
        End Get
        Set
            Me.totalImpuestosRetenidosField = value
            Me.RaisePropertyChanged("totalImpuestosRetenidos")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property totalImpuestosRetenidosSpecified() As Boolean
        Get
            Return Me.totalImpuestosRetenidosFieldSpecified
        End Get
        Set
            Me.totalImpuestosRetenidosFieldSpecified = value
            Me.RaisePropertyChanged("totalImpuestosRetenidosSpecified")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property totalImpuestosTrasladados() As Decimal
        Get
            Return Me.totalImpuestosTrasladadosField
        End Get
        Set
            Me.totalImpuestosTrasladadosField = value
            Me.RaisePropertyChanged("totalImpuestosTrasladados")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property totalImpuestosTrasladadosSpecified() As Boolean
        Get
            Return Me.totalImpuestosTrasladadosFieldSpecified
        End Get
        Set
            Me.totalImpuestosTrasladadosFieldSpecified = value
            Me.RaisePropertyChanged("totalImpuestosTrasladadosSpecified")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
Partial Public Class ComprobanteImpuestosRetencion
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private impuestoField As ComprobanteImpuestosRetencionImpuesto
    
    Private importeField As Decimal
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property impuesto() As ComprobanteImpuestosRetencionImpuesto
        Get
            Return Me.impuestoField
        End Get
        Set
            Me.impuestoField = value
            Me.RaisePropertyChanged("impuesto")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property importe() As Decimal
        Get
            Return Me.importeField
        End Get
        Set
            Me.importeField = value
            Me.RaisePropertyChanged("importe")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
Public Enum ComprobanteImpuestosRetencionImpuesto
    
    '''<remarks/>
    ISR
    
    '''<remarks/>
    IVA
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
Partial Public Class ComprobanteImpuestosTraslado
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private impuestoField As ComprobanteImpuestosTrasladoImpuesto
    
    Private tasaField As Decimal
    
    Private importeField As Decimal
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property impuesto() As ComprobanteImpuestosTrasladoImpuesto
        Get
            Return Me.impuestoField
        End Get
        Set
            Me.impuestoField = value
            Me.RaisePropertyChanged("impuesto")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property tasa() As Decimal
        Get
            Return Me.tasaField
        End Get
        Set
            Me.tasaField = value
            Me.RaisePropertyChanged("tasa")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property importe() As Decimal
        Get
            Return Me.importeField
        End Get
        Set
            Me.importeField = value
            Me.RaisePropertyChanged("importe")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
Public Enum ComprobanteImpuestosTrasladoImpuesto
    
    '''<remarks/>
    IVA
    
    '''<remarks/>
    IEPS
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
Partial Public Class ComprobanteComplemento
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private anyField() As System.Xml.XmlElement
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAnyElementAttribute()>  _
    Public Property Any() As System.Xml.XmlElement()
        Get
            Return Me.anyField
        End Get
        Set
            Me.anyField = value
            Me.RaisePropertyChanged("Any")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
Partial Public Class ComprobanteAddenda
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private anyField() As System.Xml.XmlElement
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAnyElementAttribute()>  _
    Public Property Any() As System.Xml.XmlElement()
        Get
            Return Me.anyField
        End Get
        Set
            Me.anyField = value
            Me.RaisePropertyChanged("Any")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
Public Enum ComprobanteTipoDeComprobante
    
    '''<remarks/>
    ingreso
    
    '''<remarks/>
    egreso
    
    '''<remarks/>
    traslado
End Enum
